/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use async_trait::async_trait;
use std::sync::Arc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use reqwest;

use super::{Error, configuration};

pub struct DataApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DataApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> DataApiClient {
        DataApiClient {
            configuration,
        }
    }
}

#[async_trait]
pub trait DataApi {
    async fn destroy_data(&self, objects: crate::models::DataDestroyObject) -> Result<(), Error>;
}

#[async_trait]
impl DataApi for DataApiClient {
    async fn destroy_data(&self, objects: crate::models::DataDestroyObject) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/api/v1/data/destroy", configuration.base_path);
        let mut req_builder = client.request(::reqwest::Method::DELETE, uri_str.as_str());

        req_builder = req_builder.query(&[("objects", &objects.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req).await?.error_for_status()?;
        Ok(())
    }

}
