/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountTypeProperty {
    #[serde(rename = "Default account")]
    DefaultAccount,
    #[serde(rename = "Cash account")]
    CashAccount,
    #[serde(rename = "Asset account")]
    AssetAccount,
    #[serde(rename = "Expense account")]
    ExpenseAccount,
    #[serde(rename = "Revenue account")]
    RevenueAccount,
    #[serde(rename = "Initial balance account")]
    InitialBalanceAccount,
    #[serde(rename = "Beneficiary account")]
    BeneficiaryAccount,
    #[serde(rename = "Import account")]
    ImportAccount,
    #[serde(rename = "Reconciliation account")]
    ReconciliationAccount,
    #[serde(rename = "Loan")]
    Loan,
    #[serde(rename = "Debt")]
    Debt,
    #[serde(rename = "Mortgage")]
    Mortgage,

}

impl ToString for AccountTypeProperty {
    fn to_string(&self) -> String {
        match self {
            Self::DefaultAccount => String::from("Default account"),
            Self::CashAccount => String::from("Cash account"),
            Self::AssetAccount => String::from("Asset account"),
            Self::ExpenseAccount => String::from("Expense account"),
            Self::RevenueAccount => String::from("Revenue account"),
            Self::InitialBalanceAccount => String::from("Initial balance account"),
            Self::BeneficiaryAccount => String::from("Beneficiary account"),
            Self::ImportAccount => String::from("Import account"),
            Self::ReconciliationAccount => String::from("Reconciliation account"),
            Self::Loan => String::from("Loan"),
            Self::Debt => String::from("Debt"),
            Self::Mortgage => String::from("Mortgage"),
        }
    }
}

impl std::default::Default for AccountTypeProperty {
    fn default() -> AccountTypeProperty {
        Self::DefaultAccount
    }
}




