/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

/// AccountRoleProperty : Is only mandatory when the type is asset.

/// Is only mandatory when the type is asset.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountRoleProperty {
    #[serde(rename = "defaultAsset")]
    DefaultAsset,
    #[serde(rename = "sharedAsset")]
    SharedAsset,
    #[serde(rename = "savingAsset")]
    SavingAsset,
    #[serde(rename = "ccAsset")]
    CcAsset,
    #[serde(rename = "cashWalletAsset")]
    CashWalletAsset,
}

impl std::fmt::Display for AccountRoleProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DefaultAsset => write!(f, "defaultAsset"),
            Self::SharedAsset => write!(f, "sharedAsset"),
            Self::SavingAsset => write!(f, "savingAsset"),
            Self::CcAsset => write!(f, "ccAsset"),
            Self::CashWalletAsset => write!(f, "cashWalletAsset"),
        }
    }
}

impl std::default::Default for AccountRoleProperty {
    fn default() -> AccountRoleProperty {
        Self::DefaultAsset
    }
}
