/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountTypeProperty {
    #[serde(rename = "Default account")]
    DefaultAccount,
    #[serde(rename = "Cash account")]
    CashAccount,
    #[serde(rename = "Asset account")]
    AssetAccount,
    #[serde(rename = "Expense account")]
    ExpenseAccount,
    #[serde(rename = "Revenue account")]
    RevenueAccount,
    #[serde(rename = "Initial balance account")]
    InitialBalanceAccount,
    #[serde(rename = "Beneficiary account")]
    BeneficiaryAccount,
    #[serde(rename = "Import account")]
    ImportAccount,
    #[serde(rename = "Reconciliation account")]
    ReconciliationAccount,
    #[serde(rename = "Loan")]
    Loan,
    #[serde(rename = "Debt")]
    Debt,
    #[serde(rename = "Mortgage")]
    Mortgage,
}

impl std::fmt::Display for AccountTypeProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DefaultAccount => write!(f, "Default account"),
            Self::CashAccount => write!(f, "Cash account"),
            Self::AssetAccount => write!(f, "Asset account"),
            Self::ExpenseAccount => write!(f, "Expense account"),
            Self::RevenueAccount => write!(f, "Revenue account"),
            Self::InitialBalanceAccount => write!(f, "Initial balance account"),
            Self::BeneficiaryAccount => write!(f, "Beneficiary account"),
            Self::ImportAccount => write!(f, "Import account"),
            Self::ReconciliationAccount => write!(f, "Reconciliation account"),
            Self::Loan => write!(f, "Loan"),
            Self::Debt => write!(f, "Debt"),
            Self::Mortgage => write!(f, "Mortgage"),
        }
    }
}

impl std::default::Default for AccountTypeProperty {
    fn default() -> AccountTypeProperty {
        Self::DefaultAccount
    }
}
