/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AutocompleteCurrencyCode {
    #[serde(rename = "id")]
    pub id: String,
    /// Currency name with the code between brackets.
    #[serde(rename = "name")]
    pub name: String,
    /// Currency code.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimal_places")]
    pub decimal_places: i32,
}

impl AutocompleteCurrencyCode {
    pub fn new(
        id: String,
        name: String,
        code: String,
        symbol: String,
        decimal_places: i32,
    ) -> AutocompleteCurrencyCode {
        AutocompleteCurrencyCode {
            id,
            name,
            code,
            symbol,
            decimal_places,
        }
    }
}

impl fmt::Display for AutocompleteCurrencyCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
