/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

/// AutoBudgetType : The type of auto-budget that Firefly III must create.

/// The type of auto-budget that Firefly III must create.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AutoBudgetType {
    #[serde(rename = "reset")]
    Reset,
    #[serde(rename = "rollover")]
    Rollover,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "null")]
    Null,

}

impl ToString for AutoBudgetType {
    fn to_string(&self) -> String {
        match self {
            Self::Reset => String::from("reset"),
            Self::Rollover => String::from("rollover"),
            Self::None => String::from("none"),
            Self::Null => String::from("null"),
        }
    }
}

impl std::default::Default for AutoBudgetType {
    fn default() -> AutoBudgetType {
        Self::Reset
    }
}




