/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AutocompleteAccount {
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the account found by an auto-complete search.
    #[serde(rename = "name")]
    pub name: String,
    /// Asset accounts and liabilities have a second field with the given date's account balance.
    #[serde(rename = "name_with_balance")]
    pub name_with_balance: String,
    /// Account type of the account found by the auto-complete search.
    #[serde(rename = "type")]
    pub _type: String,
    /// ID for the currency used by this account.
    #[serde(rename = "currency_id")]
    pub currency_id: String,
    /// Currency name for the currency used by this account.
    #[serde(rename = "currency_name")]
    pub currency_name: String,
    /// Currency code for the currency used by this account.
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    /// Currency symbol for the currency used by this account.
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    /// Number of decimal places for the currency used by this account.
    #[serde(rename = "currency_decimal_places")]
    pub currency_decimal_places: i32,
}

impl AutocompleteAccount {
    pub fn new(id: String, name: String, name_with_balance: String, _type: String, currency_id: String, currency_name: String, currency_code: String, currency_symbol: String, currency_decimal_places: i32) -> AutocompleteAccount {
        AutocompleteAccount {
            id,
            name,
            name_with_balance,
            _type,
            currency_id,
            currency_name,
            currency_code,
            currency_symbol,
            currency_decimal_places,
        }
    }
}


