/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillProperties {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// The name of the subscription.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.
    #[serde(
        rename = "object_has_currency_setting",
        skip_serializing_if = "Option::is_none"
    )]
    pub object_has_currency_setting: Option<bool>,
    /// The currency ID of the currency associated with this object.
    #[serde(rename = "currency_id", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<String>,
    /// The currency name of the currency associated with this object.
    #[serde(rename = "currency_name", skip_serializing_if = "Option::is_none")]
    pub currency_name: Option<String>,
    /// The currency code of the currency associated with this object.
    #[serde(rename = "currency_code", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    #[serde(rename = "currency_symbol", skip_serializing_if = "Option::is_none")]
    pub currency_symbol: Option<String>,
    #[serde(
        rename = "currency_decimal_places",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency_decimal_places: Option<i32>,
    /// The currency ID of the administration's primary currency.
    #[serde(
        rename = "primary_currency_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_id: Option<String>,
    /// The currency name of the administration's primary currency.
    #[serde(
        rename = "primary_currency_name",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_name: Option<String>,
    /// The currency code of the administration's primary currency.
    #[serde(
        rename = "primary_currency_code",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_code: Option<String>,
    /// The currency symbol of the administration's primary currency.
    #[serde(
        rename = "primary_currency_symbol",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_symbol: Option<String>,
    /// The currency decimal places of the administration's primary currency.
    #[serde(
        rename = "primary_currency_decimal_places",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_decimal_places: Option<i32>,
    /// The minimum amount that is expected for this subscription in the subscription's currency.
    #[serde(rename = "amount_min", skip_serializing_if = "Option::is_none")]
    pub amount_min: Option<String>,
    /// The minimum amount that is expected for this subscription in the administration's primary currency.
    #[serde(rename = "pc_amount_min", skip_serializing_if = "Option::is_none")]
    pub pc_amount_min: Option<String>,
    /// The maximum amount that is expected for this subscription in the subscription's currency.
    #[serde(rename = "amount_max", skip_serializing_if = "Option::is_none")]
    pub amount_max: Option<String>,
    /// The maximum amount that is expected for this subscription in the administration's primary currency.
    #[serde(rename = "pc_amount_max", skip_serializing_if = "Option::is_none")]
    pub pc_amount_max: Option<String>,
    /// The average amount that is expected for this subscription in the subscription's currency.
    #[serde(rename = "amount_avg", skip_serializing_if = "Option::is_none")]
    pub amount_avg: Option<String>,
    /// The average amount that is expected for this subscription in the administration's primary currency.
    #[serde(rename = "pc_amount_avg", skip_serializing_if = "Option::is_none")]
    pub pc_amount_avg: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// The date after which this subscription is no longer valid or applicable
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// The date before which the subscription must be renewed (or cancelled)
    #[serde(rename = "extension_date", skip_serializing_if = "Option::is_none")]
    pub extension_date: Option<String>,
    #[serde(rename = "repeat_freq", skip_serializing_if = "Option::is_none")]
    pub repeat_freq: Option<models::BillRepeatFrequency>,
    /// How often the subscription will be skipped. 1 means a bi-monthly subscription.
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i32>,
    /// If the subscription is active.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Order of the subscription.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// The group ID of the group this object is part of. NULL if no group.
    #[serde(rename = "object_group_id", skip_serializing_if = "Option::is_none")]
    pub object_group_id: Option<String>,
    /// The order of the group. At least 1, for the highest sorting.
    #[serde(rename = "object_group_order", skip_serializing_if = "Option::is_none")]
    pub object_group_order: Option<i32>,
    /// The name of the group. NULL if no group.
    #[serde(rename = "object_group_title", skip_serializing_if = "Option::is_none")]
    pub object_group_title: Option<String>,
    /// Array of past transactions when the subscription was paid.
    #[serde(rename = "paid_dates", skip_serializing_if = "Option::is_none")]
    pub paid_dates: Option<Vec<models::BillPropertiesPaidDatesInner>>,
    /// Array of future dates when the bill is expected to be paid. Autogenerated.
    #[serde(rename = "pay_dates", skip_serializing_if = "Option::is_none")]
    pub pay_dates: Option<Vec<String>>,
    /// When the subscription is expected to be due.
    #[serde(
        rename = "next_expected_match",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_expected_match: Option<String>,
    /// Formatted (locally) when the subscription is due.
    #[serde(
        rename = "next_expected_match_diff",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_expected_match_diff: Option<String>,
}

impl BillProperties {
    pub fn new() -> BillProperties {
        BillProperties {
            created_at: None,
            updated_at: None,
            name: None,
            object_has_currency_setting: None,
            currency_id: None,
            currency_name: None,
            currency_code: None,
            currency_symbol: None,
            currency_decimal_places: None,
            primary_currency_id: None,
            primary_currency_name: None,
            primary_currency_code: None,
            primary_currency_symbol: None,
            primary_currency_decimal_places: None,
            amount_min: None,
            pc_amount_min: None,
            amount_max: None,
            pc_amount_max: None,
            amount_avg: None,
            pc_amount_avg: None,
            date: None,
            end_date: None,
            extension_date: None,
            repeat_freq: None,
            skip: None,
            active: None,
            order: None,
            notes: None,
            object_group_id: None,
            object_group_order: None,
            object_group_title: None,
            paid_dates: None,
            pay_dates: None,
            next_expected_match: None,
            next_expected_match_diff: None,
        }
    }
}

impl fmt::Display for BillProperties {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
