/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BudgetStore {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Whether or not to fire the webhooks that are related to this event.
    #[serde(rename = "fire_webhooks", skip_serializing_if = "Option::is_none")]
    pub fire_webhooks: Option<bool>,
    #[serde(rename = "auto_budget_type", skip_serializing_if = "Option::is_none")]
    pub auto_budget_type: Option<models::AutoBudgetType>,
    /// Use either currency_id or currency_code. Defaults to the user's financial administration's currency.
    #[serde(
        rename = "auto_budget_currency_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_budget_currency_id: Option<String>,
    /// Use either currency_id or currency_code. Defaults to the user's financial administration's currency.
    #[serde(
        rename = "auto_budget_currency_code",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_budget_currency_code: Option<String>,
    #[serde(rename = "auto_budget_amount", skip_serializing_if = "Option::is_none")]
    pub auto_budget_amount: Option<String>,
    #[serde(rename = "auto_budget_period", skip_serializing_if = "Option::is_none")]
    pub auto_budget_period: Option<models::AutoBudgetPeriod>,
}

impl BudgetStore {
    pub fn new(name: String) -> BudgetStore {
        BudgetStore {
            name,
            active: None,
            order: None,
            notes: None,
            fire_webhooks: None,
            auto_budget_type: None,
            auto_budget_currency_id: None,
            auto_budget_currency_code: None,
            auto_budget_amount: None,
            auto_budget_period: None,
        }
    }
}

impl fmt::Display for BudgetStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
