/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CategoryProperties {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// This object never has its own currency setting, so this value is always false.
    #[serde(
        rename = "object_has_currency_setting",
        skip_serializing_if = "Option::is_none"
    )]
    pub object_has_currency_setting: Option<bool>,
    /// The currency ID of the administration's primary currency.
    #[serde(
        rename = "primary_currency_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_id: Option<String>,
    /// The currency name of the administration's primary currency.
    #[serde(
        rename = "primary_currency_name",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_name: Option<String>,
    /// The currency code of the administration's primary currency.
    #[serde(
        rename = "primary_currency_code",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_code: Option<String>,
    /// The currency symbol of the administration's primary currency.
    #[serde(
        rename = "primary_currency_symbol",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_symbol: Option<String>,
    /// The currency decimal places of the administration's primary currency.
    #[serde(
        rename = "primary_currency_decimal_places",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_currency_decimal_places: Option<i32>,
    /// Amount(s) spent in the currencies in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "spent", skip_serializing_if = "Option::is_none")]
    pub spent: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
    /// Amount(s) spent in the primary currency in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "pc_spent", skip_serializing_if = "Option::is_none")]
    pub pc_spent: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
    /// Amount(s) earned in the currencies in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "earned", skip_serializing_if = "Option::is_none")]
    pub earned: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
    /// Amount(s) earned in the primary currency in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "pc_earned", skip_serializing_if = "Option::is_none")]
    pub pc_earned: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
    /// Amount(s) transferred in the currencies in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "transferred", skip_serializing_if = "Option::is_none")]
    pub transferred: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
    /// Amount(s) transferred in primary currency in the database for this category. ONLY present when start and date are set.
    #[serde(rename = "pc_transferred", skip_serializing_if = "Option::is_none")]
    pub pc_transferred: Option<Vec<models::ArrayEntryWithCurrencyAndSum>>,
}

impl CategoryProperties {
    pub fn new(name: String) -> CategoryProperties {
        CategoryProperties {
            created_at: None,
            updated_at: None,
            name,
            notes: None,
            object_has_currency_setting: None,
            primary_currency_id: None,
            primary_currency_name: None,
            primary_currency_code: None,
            primary_currency_symbol: None,
            primary_currency_decimal_places: None,
            spent: None,
            pc_spent: None,
            earned: None,
            pc_earned: None,
            transferred: None,
            pc_transferred: None,
        }
    }
}

impl fmt::Display for CategoryProperties {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
