/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

/// RuleActionKeyword : The type of thing this action will do. A limited set is possible.

/// The type of thing this action will do. A limited set is possible.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RuleActionKeyword {
    #[serde(rename = "user_action")]
    UserAction,
    #[serde(rename = "set_category")]
    SetCategory,
    #[serde(rename = "clear_category")]
    ClearCategory,
    #[serde(rename = "set_budget")]
    SetBudget,
    #[serde(rename = "clear_budget")]
    ClearBudget,
    #[serde(rename = "add_tag")]
    AddTag,
    #[serde(rename = "remove_tag")]
    RemoveTag,
    #[serde(rename = "remove_all_tags")]
    RemoveAllTags,
    #[serde(rename = "set_description")]
    SetDescription,
    #[serde(rename = "append_description")]
    AppendDescription,
    #[serde(rename = "prepend_description")]
    PrependDescription,
    #[serde(rename = "set_source_account")]
    SetSourceAccount,
    #[serde(rename = "set_destination_account")]
    SetDestinationAccount,
    #[serde(rename = "set_notes")]
    SetNotes,
    #[serde(rename = "append_notes")]
    AppendNotes,
    #[serde(rename = "prepend_notes")]
    PrependNotes,
    #[serde(rename = "clear_notes")]
    ClearNotes,
    #[serde(rename = "link_to_bill")]
    LinkToBill,
    #[serde(rename = "convert_withdrawal")]
    ConvertWithdrawal,
    #[serde(rename = "convert_deposit")]
    ConvertDeposit,
    #[serde(rename = "convert_transfer")]
    ConvertTransfer,
    #[serde(rename = "delete_transaction")]
    DeleteTransaction,

}

impl ToString for RuleActionKeyword {
    fn to_string(&self) -> String {
        match self {
            Self::UserAction => String::from("user_action"),
            Self::SetCategory => String::from("set_category"),
            Self::ClearCategory => String::from("clear_category"),
            Self::SetBudget => String::from("set_budget"),
            Self::ClearBudget => String::from("clear_budget"),
            Self::AddTag => String::from("add_tag"),
            Self::RemoveTag => String::from("remove_tag"),
            Self::RemoveAllTags => String::from("remove_all_tags"),
            Self::SetDescription => String::from("set_description"),
            Self::AppendDescription => String::from("append_description"),
            Self::PrependDescription => String::from("prepend_description"),
            Self::SetSourceAccount => String::from("set_source_account"),
            Self::SetDestinationAccount => String::from("set_destination_account"),
            Self::SetNotes => String::from("set_notes"),
            Self::AppendNotes => String::from("append_notes"),
            Self::PrependNotes => String::from("prepend_notes"),
            Self::ClearNotes => String::from("clear_notes"),
            Self::LinkToBill => String::from("link_to_bill"),
            Self::ConvertWithdrawal => String::from("convert_withdrawal"),
            Self::ConvertDeposit => String::from("convert_deposit"),
            Self::ConvertTransfer => String::from("convert_transfer"),
            Self::DeleteTransaction => String::from("delete_transaction"),
        }
    }
}

impl std::default::Default for RuleActionKeyword {
    fn default() -> RuleActionKeyword {
        Self::UserAction
    }
}




