/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RuleAction {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::RuleActionKeyword,
    /// The accompanying value the action will set, change or update. Can be empty, but for some types this value is mandatory.
    #[serde(rename = "value")]
    pub value: Option<String>,
    /// Order of the action
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    /// If the action is active. Defaults to true.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// When true, other actions will not be fired after this action has fired. Defaults to false.
    #[serde(rename = "stop_processing", skip_serializing_if = "Option::is_none")]
    pub stop_processing: Option<bool>,
}

impl RuleAction {
    pub fn new(_type: crate::models::RuleActionKeyword, value: Option<String>) -> RuleAction {
        RuleAction {
            id: None,
            created_at: None,
            updated_at: None,
            _type,
            value,
            order: None,
            active: None,
            stop_processing: None,
        }
    }
}


