/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

/// ShortAccountTypeProperty : Can only be one one these account types. import, initial-balance and reconciliation cannot be set manually.

/// Can only be one one these account types. import, initial-balance and reconciliation cannot be set manually.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShortAccountTypeProperty {
    #[serde(rename = "asset")]
    Asset,
    #[serde(rename = "expense")]
    Expense,
    #[serde(rename = "import")]
    Import,
    #[serde(rename = "revenue")]
    Revenue,
    #[serde(rename = "cash")]
    Cash,
    #[serde(rename = "liability")]
    Liability,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "initial-balance")]
    InitialBalance,
    #[serde(rename = "reconciliation")]
    Reconciliation,
}

impl std::fmt::Display for ShortAccountTypeProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Asset => write!(f, "asset"),
            Self::Expense => write!(f, "expense"),
            Self::Import => write!(f, "import"),
            Self::Revenue => write!(f, "revenue"),
            Self::Cash => write!(f, "cash"),
            Self::Liability => write!(f, "liability"),
            Self::Liabilities => write!(f, "liabilities"),
            Self::InitialBalance => write!(f, "initial-balance"),
            Self::Reconciliation => write!(f, "reconciliation"),
        }
    }
}

impl std::default::Default for ShortAccountTypeProperty {
    fn default() -> ShortAccountTypeProperty {
        Self::Asset
    }
}
