/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionLinkUpdate {
    /// The link type ID to use. Use this field OR use the link_type_name field.
    #[serde(rename = "link_type_id", skip_serializing_if = "Option::is_none")]
    pub link_type_id: Option<String>,
    /// The link type name to use. Use this field OR use the link_type_id field.
    #[serde(rename = "link_type_name", skip_serializing_if = "Option::is_none")]
    pub link_type_name: Option<String>,
    /// The inward transaction transaction_journal_id for the link. This becomes the 'is paid by' transaction of the set.
    #[serde(rename = "inward_id", skip_serializing_if = "Option::is_none")]
    pub inward_id: Option<String>,
    /// The outward transaction transaction_journal_id for the link. This becomes the 'pays for' transaction of the set.
    #[serde(rename = "outward_id", skip_serializing_if = "Option::is_none")]
    pub outward_id: Option<String>,
    /// Optional. Some notes. If you submit an empty string the current notes will be removed
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl TransactionLinkUpdate {
    pub fn new() -> TransactionLinkUpdate {
        TransactionLinkUpdate {
            link_type_id: None,
            link_type_name: None,
            inward_id: None,
            outward_id: None,
            notes: None,
        }
    }
}


