/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionLinkStore {
    /// The link type ID to use. You can also use the link_type_name field.
    #[serde(rename = "link_type_id")]
    pub link_type_id: String,
    /// The link type name to use. You can also use the link_type_id field.
    #[serde(rename = "link_type_name", skip_serializing_if = "Option::is_none")]
    pub link_type_name: Option<String>,
    /// The inward transaction transaction_journal_id for the link. This becomes the 'is paid by' transaction of the set.
    #[serde(rename = "inward_id")]
    pub inward_id: String,
    /// The outward transaction transaction_journal_id for the link. This becomes the 'pays for' transaction of the set.
    #[serde(rename = "outward_id")]
    pub outward_id: String,
    /// Optional. Some notes.
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl TransactionLinkStore {
    pub fn new(
        link_type_id: String,
        inward_id: String,
        outward_id: String,
    ) -> TransactionLinkStore {
        TransactionLinkStore {
            link_type_id,
            link_type_name: None,
            inward_id,
            outward_id,
            notes: None,
        }
    }
}

impl fmt::Display for TransactionLinkStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
