/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionStore {
    /// Break if the submitted transaction exists already.
    #[serde(
        rename = "error_if_duplicate_hash",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_if_duplicate_hash: Option<bool>,
    /// Whether or not to apply rules when submitting transaction.
    #[serde(rename = "apply_rules", skip_serializing_if = "Option::is_none")]
    pub apply_rules: Option<bool>,
    /// Whether or not to fire the webhooks that are related to this event.
    #[serde(rename = "fire_webhooks", skip_serializing_if = "Option::is_none")]
    pub fire_webhooks: Option<bool>,
    /// Title of the transaction if it has been split in more than one piece. Empty otherwise.
    #[serde(rename = "group_title", skip_serializing_if = "Option::is_none")]
    pub group_title: Option<String>,
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::TransactionSplitStore>,
}

impl TransactionStore {
    pub fn new(transactions: Vec<models::TransactionSplitStore>) -> TransactionStore {
        TransactionStore {
            error_if_duplicate_hash: None,
            apply_rules: None,
            fire_webhooks: None,
            group_title: None,
            transactions,
        }
    }
}

impl fmt::Display for TransactionStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{{{{}}}}"),
        }
    }
}
