/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]

use crate::models::{self, *};
use std::fmt;

/// UserBlockedCodeProperty : If you say the user must be blocked, this will be the reason code.

/// If you say the user must be blocked, this will be the reason code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserBlockedCodeProperty {
    #[serde(rename = "email_changed")]
    EmailChanged,
}

impl std::fmt::Display for UserBlockedCodeProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::EmailChanged => write!(f, "email_changed"),
        }
    }
}

impl std::default::Default for UserBlockedCodeProperty {
    fn default() -> UserBlockedCodeProperty {
        Self::EmailChanged
    }
}
