/*
 * Firefly III API v1.5.5
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-01-30T05:47:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

/// WebhookResponse : Indicator for what Firefly III will deliver to the webhook URL.

/// Indicator for what Firefly III will deliver to the webhook URL.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookResponse {
    #[serde(rename = "RESPONSE_TRANSACTIONS")]
    TRANSACTIONS,
    #[serde(rename = "RESPONSE_ACCOUNTS")]
    ACCOUNTS,
    #[serde(rename = "RESPONSE_NONE")]
    NONE,

}

impl ToString for WebhookResponse {
    fn to_string(&self) -> String {
        match self {
            Self::TRANSACTIONS => String::from("RESPONSE_TRANSACTIONS"),
            Self::ACCOUNTS => String::from("RESPONSE_ACCOUNTS"),
            Self::NONE => String::from("RESPONSE_NONE"),
        }
    }
}

impl std::default::Default for WebhookResponse {
    fn default() -> WebhookResponse {
        Self::TRANSACTIONS
    }
}




